version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - '3000:3000'
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    command: npm run start:dev
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules

  employee-service:
    build: ./employee-service
    container_name: employee-service
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    command: npm run start:dev
    volumes:
      - ./employee-service:/usr/src/app
      - /usr/src/app/node_modules
